name = "aoc"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_http = ">= 3.7.1 and < 4.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
glint = ">= 1.1.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"
humanise = ">= 1.0.2 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
atomic_array = ">= 1.0.0 and < 2.0.0"
glearray = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 0.16.0 and < 1.0.0"
rememo = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
